java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
java -jar dist/DDOS_MARKING.jar
